apiVersion: v1
kind: Secret
metadata:
  name: k8s-doctor-readonly-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: k8s-doctor-readonly
type: kubernetes.io/service-account-token
